const sharkList=d=>Array.isArray(d)?d:Array.isArray(d?.data)?d.data:Array.isArray(d?.data?.list)?d.data.list:Array.isArray(d?.data?.items)?d.data.items:Array.isArray(d?.result)?d.result:[];
async function sharkCall(c,method,path,params={}){
 const stamp=String(Date.now()),query=method==='GET'?new URLSearchParams({...params,timestamp:stamp}).toString():'',body=method==='GET'?'':JSON.stringify({...params,timestamp:stamp}),signed=method==='GET'?query:body;
 let key=await crypto.subtle.importKey('raw',enc.encode(c.secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),signature=hex(await crypto.subtle.sign('HMAC',key,enc.encode(signed))),response;
 try{response=await fetch('https://api.sharkexchange.in'+path+(query?'?'+query:''),{method,headers:{'api-key':c.key,signature,accept:'application/json','content-type':'application/json'},body:body||undefined,signal:AbortSignal.timeout(15000)})}catch(e){throw Error('NETWORK_UNKNOWN: check the exchange before repeating this action')}
 let data;try{data=await response.json()}catch(e){throw Error('NETWORK_UNKNOWN: unreadable exchange response')}
 if(!response.ok||data?.success===false){let code=String(data?.code??data?.error?.code??response.status).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80);throw Error('Shark rejected request: '+code)}return data;
}
async function sharkProduct(symbol){if(!/^[A-Z0-9]{3,32}$/.test(symbol))throw Error('Invalid coin');let r=await fetch('https://api.sharkexchange.in/v1/exchange/exchangeInfo',{signal:AbortSignal.timeout(15000)}),d=await r.json(),p=d.contracts?.find(x=>x.name===symbol&&x.contractType==='PERPETUAL');if(!r.ok||!p||!p.orderTypes?.includes('LIMIT'))throw Error('Contract not available for limit trading');return p}
function sharkPrice(value,p){let n=Number(value),step=10**(-Number(p.pricePrecision));if(!Number.isFinite(n)||n<=0||!Number.isFinite(step)||step<=0||Math.abs(n/step-Math.round(n/step))>1e-6)throw Error('Use a positive price at the exchange tick size');return n}
function sharkQuantity(value,p){let n=Number(value),step=10**(-Number(p.quantityPrecision)),filter=p.filters?.find(x=>x.filterType==='LIMIT_QTY_SIZE');if(!Number.isFinite(n)||n<=0||!Number.isFinite(step)||step<=0||Math.abs(n/step-Math.round(n/step))>1e-6||n<Number(filter?.minQty)||n>Number(filter?.maxQty))throw Error('Quantity is outside this contract’s limit or step');return n}
async function sharkState(c){let [positions,orders,trades]=await Promise.all([sharkCall(c,'GET','/v1/positions/OPEN',{sortOrder:'desc',pageSize:'100'}),sharkCall(c,'GET','/v1/order/open-orders',{pageSize:'100',sortOrder:'desc'}),sharkCall(c,'GET','/v1/user-data/trade-history',{pageSize:'100',sortOrder:'desc'})]);let p=sharkList(positions),o=sharkList(orders),t=sharkList(trades);if((positions.data?.totalCount??0)>p.length||(orders.data?.totalCount??0)>o.length)throw Error('More than 100 active positions or orders; use Shark directly until the full account can be verified');return {positions:p,orders:o,trades:t}}
async function prepareShark(c,input){let action=input.action,symbol=String(input.symbol??'').toUpperCase(),p=await sharkProduct(symbol),state=await sharkState(c),pos=state.positions.find(x=>x.contractPair===symbol&&x.positionStatus==='OPEN'),existing=state.orders.filter(x=>x.symbol===symbol),base={action,symbol};
 if(action==='cancel'){let order=existing.find(x=>x.clientOrderId===input.orderId);if(!order)throw Error('Order is no longer open');return {...base,method:'DELETE',path:'/v1/order/delete-order',body:{clientOrderId:order.clientOrderId},summary:{action:'Cancel Shark order',symbol,orderId:order.clientOrderId,quantity:order.orderAmount,side:order.side}}}
 if(action==='close'){if(!pos||!(Number(pos.quantity)>0))throw Error('No open position to close');let side=pos.positionType==='LONG'?'SELL':'BUY';return {...base,method:'POST',path:'/v1/order/place-order',body:{placeType:'POSITION',positionId:pos.positionId,quantity:Number(pos.quantity),side,symbol,reduceOnly:true,marginAsset:pos.marginAsset,type:'MARKET'},summary:{action:'Close Shark position at market',symbol,quantity:Number(pos.quantity),side,positionId:pos.positionId}}}
 let stop=sharkPrice(input.stop,p),target=sharkPrice(input.target,p);
 if(action==='protect'){if(!pos)throw Error('No open position to protect');if(existing.some(x=>x.placeType==='POSITION'&&/STOP_LOSS|TAKE_PROFIT/.test(x.subType??'')))throw Error('Protection already exists. Manage those orders before adding another set.');let side=pos.positionType==='LONG'?1:-1,entry=Number(pos.entryPrice),quantity=sharkQuantity(pos.quantity,p);if(!(side*(entry-stop)>0&&side*(target-entry)>0))throw Error('Stop and target must surround the position entry');return {...base,method:'POST',path:'/v2/order/split-tp-sl',body:{positionId:pos.positionId,splitTakeProfitOrders:[{quantity,price:target}],splitStopLossOrders:[{quantity,price:stop}]},summary:{action:'Add Shark stop and target',symbol,positionId:pos.positionId,quantity,stop,target}}}
 if(action!=='open')throw Error('Unsupported action');if(pos||existing.length)throw Error('Position or order already exists for this coin. Manage it before changing leverage.');let side=input.side==='BUY'?1:input.side==='SELL'?-1:0,entry=sharkPrice(input.entry,p),quantity=sharkQuantity(input.quantity,p),leverage=Number(input.leverage),marginAsset=String(input.marginAsset??'INR');if(!side||!Number.isInteger(leverage)||leverage<1||leverage>Number(p.maxLeverage)||!p.marginAssetsSupported?.includes(marginAsset))throw Error('Invalid side, leverage or margin asset');if(!(side*(entry-stop)>0&&side*(target-entry)>0))throw Error('Stop and target must surround entry');let minNotional=Number(p.filters?.find(x=>x.filterType==='MIN_NOTIONAL')?.notional??0);if(quantity*entry<minNotional)throw Error('Below exchange minimum notional');return {...base,leverage,method:'POST',path:'/v1/order/place-order',body:{placeType:'ORDER_FORM',quantity,side:input.side,symbol,reduceOnly:false,marginAsset,type:'LIMIT',price:entry,stopLossPrice:stop,takeProfitPrice:target,deviceType:'WEB',userCategory:'EXTERNAL'},summary:{action:'New Shark LIMIT order with stop and target',symbol,side:input.side,quantity,entry,stop,target,leverage,marginAsset}}}
async function sharkDeskRoute(request,env){const u=new URL(request.url),owner=request.headers.get('oai-authenticated-user-id'),email=request.headers.get('oai-authenticated-user-email');if(!owner||!env.TRADE_OWNER_EMAIL||email!==env.TRADE_OWNER_EMAIL)return json({error:'Owner sign-in required'},403);if(!env.DB||!env.TRADE_SESSION_SECRET)return json({error:'Trading connection unavailable'},503);if(request.method!=='GET'&&(request.headers.get('origin')!==u.origin||!request.headers.get('content-type')?.startsWith('application/json')))return json({error:'Same-origin JSON request required'},403);let q=(sql,...args)=>env.DB.prepare(sql).bind(...args),route=u.pathname.slice('/api/shark-desk/'.length),sid=request.headers.get('cookie')?.match(/(?:^|; )radar_shark=([a-f0-9-]+)/)?.[1],input={};if(request.method!=='GET'){if(+(request.headers.get('content-length')||0)>8192)return json({error:'Request too large'},413);try{input=await request.json()}catch(e){return json({error:'Invalid JSON'},400)}}let secure=u.hostname==='localhost'?'':' Secure;';try{
 if(route==='connect'&&request.method==='POST'){if(typeof input.key!=='string'||typeof input.secret!=='string'||input.key.length<8||input.key.length>256||input.secret.length<8||input.secret.length>256)throw Error('Enter Shark API key and secret');await sharkCall(input,'GET','/v1/positions/OPEN',{pageSize:'1'});let id=crypto.randomUUID(),expires=8640000000000000;await q('DELETE FROM shark_sessions WHERE owner = ?',owner).run();await q('INSERT INTO shark_sessions(id,owner,cipher,expires,trading) VALUES(?,?,?,?,?)',id,owner,await seal({key:input.key,secret:input.secret},env.TRADE_SESSION_SECRET),expires,input.trading===true?1:0).run();return json({connected:true,trading:input.trading===true,expires},200,{'set-cookie':`radar_shark=${id}; HttpOnly;${secure} SameSite=Strict; Path=/api/shark-desk; Max-Age=34560000`})}
 if(route==='disconnect'&&request.method==='POST'){await q('DELETE FROM shark_sessions WHERE owner = ?',owner).run();return json({connected:false},200,{'set-cookie':`radar_shark=; HttpOnly;${secure} SameSite=Strict; Path=/api/shark-desk; Max-Age=0`})}
 let session=await q('SELECT * FROM shark_sessions WHERE owner = ? AND expires > ?',owner,Date.now()).first();if(!session)return json({error:'Connect Shark to see your account.'},401);sid=session.id;let c=await unseal(session.cipher,env.TRADE_SESSION_SECRET);
 if(route==='account'&&request.method==='GET'){let [state,inr,usdt]=await Promise.all([sharkState(c),sharkCall(c,'GET','/v1/wallet/futures-wallet/details',{marginAsset:'INR'}).catch(()=>null),sharkCall(c,'GET','/v1/wallet/futures-wallet/details',{marginAsset:'USDT'}).catch(()=>null)]);let wallets=[inr,usdt].map((raw,i)=>{let w=raw?.data??raw,available=Number(w?.maxWithdrawableBalance??w?.withdrawableBalance);return {asset:i?'USDT':'INR',available,total:Number(w?.walletBalance)}}).filter(w=>Number.isFinite(w.available)&&w.available>=0);return json({connected:true,trading:!!session.trading,expires:session.expires,asOf:Date.now(),wallets,...state})}
 if(route==='permissions'&&request.method==='POST'){if(typeof input.trading!=='boolean')throw Error('Choose whether to enable reviewed orders');await q('UPDATE shark_sessions SET trading = ? WHERE id = ? AND owner = ?',input.trading?1:0,sid,owner).run();return json({trading:input.trading})}
if(!session.trading)return json({error:'Reconnect with reviewed order actions enabled'},403);
 if(route==='review'&&request.method==='POST'){let symbol=String(input.symbol??'').toUpperCase(),pending=await q("SELECT id FROM trade_intents WHERE owner = ? AND symbol = ? AND status IN ('submitting','unknown')",owner,'shark:'+symbol).first();if(pending)throw Error('A previous Shark request has an unconfirmed outcome. Check the exchange before another action for this coin.');let prepared=await prepareShark(c,{...input,symbol}),id=crypto.randomUUID().replaceAll('-',''),expires=Date.now()+60000;await q('INSERT INTO trade_intents(id,owner,session,symbol,payload,status,expires) VALUES(?,?,?,?,?,?,?)',id,owner,sid,'shark:'+symbol,JSON.stringify(prepared),'review',expires).run();return json({id,expires,summary:prepared.summary})}
 if(route==='submit'&&request.method==='POST'){if(input.confirm!==true)throw Error('Explicit confirmation required');let intent=await q('SELECT * FROM trade_intents WHERE id = ? AND owner = ? AND session = ? AND symbol LIKE ?',String(input.id),owner,sid,'shark:%').first();if(!intent)throw Error('Review not found');if(intent.status!=='review')return json({error:'Already submitted. Refresh the account before taking another action.'},409);if(intent.expires<Date.now())throw Error('Review expired');let claimed=await q("UPDATE trade_intents SET status = 'submitting' WHERE id = ? AND status = 'review'",intent.id).run();if(claimed.meta.changes!==1)return json({error:'Already handled'},409);let p=JSON.parse(intent.payload),posted=false;try{let fresh=await prepareShark(c,{action:p.action,symbol:p.symbol,orderId:p.body.clientOrderId,entry:p.summary.entry,stop:p.summary.stop,target:p.summary.target,quantity:p.body.quantity,side:p.body.side,leverage:p.leverage,marginAsset:p.body.marginAsset});if(JSON.stringify(fresh.summary)!==JSON.stringify(p.summary))throw Error('Exchange state changed after review. Review again.');if(p.action==='open'){await sharkCall(c,'POST','/v1/exchange/update/leverage',{leverage:p.leverage,contractName:p.symbol})}posted=true;let result=await sharkCall(c,p.method,p.path,p.body);if(p.action==='protect'&&result.rejectedOrderCount>0)throw Error('Some protection orders were rejected. Check Shark orders immediately.');await q("UPDATE trade_intents SET status = 'accepted', result = ? WHERE id = ?",JSON.stringify(result),intent.id).run();return json({accepted:true,note:'Shark accepted the action. Refresh account and verify fills and protective orders.',result})}catch(e){let status=posted&&(e.message.startsWith('NETWORK_UNKNOWN')||e.message.includes('protection orders were rejected'))?'unknown':'failed';await q('UPDATE trade_intents SET status = ?, result = ? WHERE id = ?',status,e.message,intent.id).run();return json({error:e.message,status},502)}}return json({error:'Unknown trading route'},404)
 }catch(e){return json({error:e.message||'Shark account service unavailable'},400)}}
