import assert from 'node:assert/strict';
import '../dist/customer-flow.js';
const F=globalThis.CustomerFlow,now=1000000,ready={now,quoteAt:now,accountAt:now,connected:true,rules:true,exchange:'delta',symbol:'BTCUSD'};
let draft=F.create('delta','BTCUSD');
assert.match(F.gate(draft,ready),/Set entry/);
draft=F.strategy(draft,{entry:100,stop:95,target:110,side:1,confirmed:false},now,now+60000);
assert.match(F.gate(draft,ready),/Forming/);
draft=F.strategy(draft,{entry:100,stop:95,target:110,side:1,confirmed:true},now,now+60000);
assert.equal(F.gate(draft,ready),null);
assert.match(F.gate(draft,{...ready,now:now+60001}),/expired/);
assert.match(F.gate(draft,{...ready,quoteAt:now-15001}),/Market data is stale/);
assert.match(F.gate(draft,{...ready,accountAt:now-30001}),/balance is stale/);
assert.match(F.gate(draft,{...ready,symbol:'ETHUSD'}),/selected coin/);
assert.match(F.gate(draft,{...ready,exchange:'shark'}),/selected coin/);
assert.match(F.gate(draft,{...ready,connected:false}),/Connect/);
assert.match(F.gate(draft,{...ready,rules:false}),/Contract/);
assert.match(F.gate(draft,{...ready,quoteAt:now+1001}),/stale/);
const context={exchange:'delta',symbol:'BTCUSD',action:'open',revision:draft.revision};
assert.equal(F.accepted(draft,{...context,symbol:'ETHUSD'}),draft);
assert.equal(F.accepted(draft,{...context,action:'close'}),draft);
let edited=F.edit(draft,{target:115});
assert.equal(F.accepted(edited,context),edited,'An accepted earlier review must not erase a newer edit');
let cleared=F.accepted(draft,context);
assert.equal(cleared.cleared,true);assert.equal(F.plan(cleared),null);
assert.equal(F.accepted(cleared,context),cleared,'Duplicate result is harmless');
let manual=F.edit(cleared,{entry:100,stop:95,target:115,side:1});
assert.equal(F.gate(manual,ready),null);assert.equal(manual.source,'manual');
assert.equal(F.plan(F.edit(manual,{stop:105})),null);
assert.equal(F.plan(F.edit(manual,{entry:NaN})),null);
assert.ok(F.plan(F.edit(manual,{side:-1,stop:105,target:90})));
console.log('PASS customer flow: confirmations, price/account freshness, symbol isolation, draft edits and accepted-order clearing');
