import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {createHmac,webcrypto} from 'node:crypto';
let sql=new DatabaseSync(':memory:');for(let file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
let DB={prepare(query){return {bind(...args){return {run:async()=>({meta:{changes:sql.prepare(query).run(...args).changes}}),first:async()=>sql.prepare(query).get(...args)??null}}}}};
let calls=[],contract={name:'BTCUSDT',contractType:'PERPETUAL',orderTypes:['LIMIT','MARKET'],pricePrecision:'1',quantityPrecision:'3',maxLeverage:'100',marginAssetsSupported:['INR','USDT'],filters:[{filterType:'LIMIT_QTY_SIZE',minQty:'0.001',maxQty:'50'},{filterType:'MIN_NOTIONAL',notional:'100'}]};
async function fetch(url,o={}){let u=new URL(url),method=o.method??'GET';calls.push({path:u.pathname,method,body:o.body});if(u.pathname==='/v1/exchange/exchangeInfo')return Response.json({contracts:[contract]});let signed=method==='GET'?u.search.slice(1):o.body;assert.equal(o.headers.signature,createHmac('sha256','fake-secret-value').update(signed).digest('hex'));
 if(u.pathname==='/v1/positions/OPEN')return Response.json({data:[]});if(u.pathname==='/v1/order/open-orders')return Response.json({data:[]});if(u.pathname==='/v1/user-data/trade-history')return Response.json({data:[]});if(u.pathname==='/v1/wallet/futures-wallet/details')return Response.json({data:{marginAsset:u.searchParams.get('marginAsset'),maxWithdrawableBalance:u.searchParams.get('marginAsset')==='INR'?'1000':'25',walletBalance:u.searchParams.get('marginAsset')==='INR'?'1200':'30'}});if(u.pathname==='/v1/exchange/update/leverage')return Response.json({updatedLeverage:5});if(u.pathname==='/v1/order/place-order'){let b=JSON.parse(o.body);assert.equal(b.reduceOnly,false);assert.equal(b.type,'LIMIT');assert.equal(b.stopLossPrice,99000);assert.equal(b.takeProfitPrice,102000);assert.equal(b.marginAsset,'INR');return Response.json({success:true,clientOrderId:'accepted-42'})}throw Error('Unexpected '+url)}
let ctx=vm.createContext({TextEncoder,TextDecoder,Response,URL,URLSearchParams,AbortSignal,crypto:webcrypto,fetch,Uint8Array,Date,JSON,Number,String,Math,Error,Promise});vm.runInContext(fs.readFileSync('delta-desk.js','utf8')+'\n'+fs.readFileSync('shark-desk.js','utf8')+'\nthis.handler=sharkDeskRoute;',ctx);
let env={DB,TRADE_OWNER_EMAIL:'owner@example.test',TRADE_SESSION_SECRET:'server-only-encryption-key'},cookie='';let req=(route,body,extra={})=>new Request('https://radar.test/api/shark-desk/'+route,{method:body?'POST':'GET',headers:{'oai-authenticated-user-id':'owner-id','oai-authenticated-user-email':'owner@example.test',origin:'https://radar.test','content-type':'application/json',cookie,...extra},body:body?JSON.stringify(body):undefined});
assert.equal((await ctx.handler(req('connect',{key:'fake-api-key',secret:'fake-secret-value'},{origin:'https://evil.test'}),env)).status,403);
let connected=await ctx.handler(req('connect',{key:'fake-api-key',secret:'fake-secret-value',trading:true}),env);assert.equal(connected.status,200);cookie=connected.headers.get('set-cookie').split(';')[0];assert(!sql.prepare('SELECT cipher FROM shark_sessions').get().cipher.includes('fake-secret'));
let account=await (await ctx.handler(req('account'),env)).json();assert.deepEqual(account.positions,[]);assert.deepEqual(account.orders,[]);assert.deepEqual(account.wallets,[{asset:'INR',available:1000,total:1200},{asset:'USDT',available:25,total:30}]);
let body={action:'open',symbol:'BTCUSDT',entry:100000,stop:99000,target:102000,quantity:.002,side:'BUY',leverage:5,marginAsset:'INR'};assert.equal((await ctx.handler(req('review',{...body,stop:100001}),env)).status,400);
let reviewed=await (await ctx.handler(req('review',body),env)).json();assert(reviewed.id);let submitted=await Promise.all([ctx.handler(req('submit',{id:reviewed.id,confirm:true}),env),ctx.handler(req('submit',{id:reviewed.id,confirm:true}),env)]);assert.deepEqual(submitted.map(x=>x.status).sort(),[200,409]);assert.equal(calls.filter(x=>x.path==='/v1/order/place-order').length,1);assert.equal(calls.filter(x=>x.path==='/v1/exchange/update/leverage').length,1);assert(!calls.some(x=>/withdraw/i.test(x.path)));
await ctx.handler(req('disconnect',{}),env);assert.equal((await ctx.handler(req('account'),env)).status,401);console.log('PASS: Shark owner/CSRF, encrypted session, exact signature, order with stop/target, leverage, duplicate lock, no withdrawal route');
